### ISSUE TITLE
new authtoken

### ISSUE THREAD

**Issue by getabc** [SirLagz/TelstraSMS.py#1]
Hello,

If there is an empty "/tmp/telstraauth" auth token file the script fails.

```
root@control:/usr/lib/zabbix/alertscripts# ./telstrasms.py xxxxxxxx Hello
Traceback (most recent call last):
  File "./telstrasms.py", line 24, in <module>
    dicttoken = json.loads(filetoken)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by SirLagz** [comment]
I've added in some checks to check for invalid JSON now.

**Comment by getabc** [comment]
Thank you good sir :)
